### ISSUE TITLE
予約一覧部分をスクロール可能にする機能実装

### ISSUE THREAD

**Issue by ak-kitsuda** [ak-kitsuda/meeting-room-booking-system#1]
## 概要
現在、予約件数が多くなると予約一覧が画面の縦方向に延びていき、ページ全体が長くなってしまいます。ユーザビリティを向上させるため、予約一覧部分を固定高さにして内部スクロール可能にする機能が必要です。

## 現状の問題点
- 予約件数が増えると、ページ全体が縦に長くなりすぎる
- 新しい予約を追加する際、予約一覧まで下にスクロールする必要がある
- 全体のレイアウトが崩れやすい

## 期待する動作
- 予約一覧(`reservations-list`)が一定の高さで固定される
- 予約件数が多い場合、予約一覧部分のみがスクロール可能になる
- スクロールバーがモダンなデザインに統一される

## 技術的な実装案
CSSの修正案：
```css
.reservations-list {
    margin-top: 20px;
    max-height: 400px; /* 固定の高さを設定 */
    overflow-y: auto; /* 縦方向にスクロール可能に */
    padding-right: 5px; /* スクロールバー用の余白 */
}

/* モダンなスクロールバーのスタイル（オプション） */
.reservations-list::-webkit-scrollbar {
    width: 8px;
}

.reservations-list::-webkit-scrollbar-track {
    background: #f1f1f1;
    border-radius: 4px;
}

.reservations-list::-webkit-scrollbar-thumb {
    background: var(--primary-color);
    border-radius: 4px;
}
```

## 関連ファイル
- `style.css`: 予約一覧のスタイル定義
- `index.html`: 予約一覧の構造

## 優先度
中程度 - ユーザビリティ向上のために重要な機能
